// Success
export const SET_LOADING = 'MAIN/SET_LOADING';
export const FETCH_COMPANY_DATA = 'MAIN/FETCH_COMPANY_DATA';

// Fail
export const FETCH_COMPANY_DATA_FAIL = 'MAIN/FETCH_COMPANY_DATA_FAIL';
export const FETCH_COMPANY_REPO_DATA_FAIL = 'MAIN/FETCH_COMPANY_REPO_DATA_FAIL';
export const FETCH_COMPANY_WIKI_DATA_FAIL = 'MAIN/FETCH_COMPANY_WIKI_DATA_FAIL';
export const FETCH_COMPANY_GITHUB_DATA_FAIL = 'MAIN/FETCH_COMPANY_GITHUB_DATA_FAIL';
export const FETCH_COMPANY_DUCKDUCKGO_DATA_FAIL = 'MAIN/FETCH_COMPANY_DUCKDUCKGO_DATA_FAIL';
